services:
  postgres:
    image: postgres:15.4
    container_name: gymflow-postgres
    environment:
      POSTGRES_DB: gymflow
      POSTGRES_USER: gymflow
      POSTGRES_PASSWORD: gymflow
    ports:
      - "5432:5432"
    volumes:
      - gymflow_pgdata:/var/lib/postgresql/data

volumes:
  gymflow_pgdata:
